//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaGaan.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dier
    {
        public Dier()
        {
            this.Taak = new HashSet<Taak>();
        }
    
        public int Id { get; set; }
        public string DierNaam { get; set; }
        public string DierSoort { get; set; }
        public System.DateTime GeboorteDatum { get; set; }
        public int VoerProductId { get; set; }
    
        public virtual ICollection<Taak> Taak { get; set; }
        public virtual Product Product { get; set; }
    }
}
