//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaGaan.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evenement
    {
        public Evenement()
        {
            this.Reservering = new HashSet<Reservering>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public string Soort { get; set; }
        public System.DateTime Datum { get; set; }
        public int MaxAantalPersonen { get; set; }
        public int Korting { get; set; }
    
        public virtual ICollection<Reservering> Reservering { get; set; }
    }
}
