//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaGaan.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persoon
    {
        public Persoon()
        {
            this.Werkrooster = new HashSet<Werkrooster>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public string Email { get; set; }
        public string Wachtwoord { get; set; }
        public string Telefoonnummer { get; set; }
        public string Woonplaats { get; set; }
        public string Postcode { get; set; }
        public string Straatnaam { get; set; }
        public string Huisnummer { get; set; }
        public System.DateTime Startdatum { get; set; }
        public int Vergoeding { get; set; }
        public string Functie { get; set; }
        public System.DateTime GeboorteDatum { get; set; }
    
        public virtual ICollection<Werkrooster> Werkrooster { get; set; }
    }
}
