//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaGaan.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservering
    {
        public int Id { get; set; }
        public int EvenementId { get; set; }
        public string Naam { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Evenement Evenement { get; set; }
        public virtual VerkoopOrder VerkoopOrder { get; set; }
    }
}
