//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaGaan.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taak
    {
        public Taak()
        {
            this.Werkrooster = new HashSet<Werkrooster>();
        }
    
        public int Id { get; set; }
        public string Omschrijving { get; set; }
    
        public virtual ICollection<Werkrooster> Werkrooster { get; set; }
        public virtual Dier Dier { get; set; }
    }
}
