//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaGaan.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Werkrooster
    {
        public int Id { get; set; }
        public int PersoonId { get; set; }
        public System.DateTime Datum { get; set; }
        public System.TimeSpan BeginTijd { get; set; }
        public System.TimeSpan EindTijd { get; set; }
        public int TaakId { get; set; }
    
        public virtual Persoon Persoon { get; set; }
        public virtual Taak Taak { get; set; }
    }
}
